name: Generate Snake Game ğŸ

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/ocean.gif
          svg_out_path: dist/github-snake.svg
          
      - name: Move and Rename files
        run: |
          mkdir -p output
          cp dist/github-snake.svg output/
          cp dist/ocean.gif output/
          
      - name: Push to GitHub
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: output
          folder: output
